# ===================================================================
# Spring Boot configuration for the "dev" profile.
# This configuration overrides the application.yml file.

#Standard Spring Boot properties.
logging:
  level:
    ROOT: DEBUG
    sn.ouznoreyni: DEBUG
    org.hibernate.SQL: DEBUG
    sn.ouznoreyni.kinect: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 8080


# ===================================================================
# Application specific properties







